# Handling Missing Values

In [14]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
import numpy as np
from scipy.stats import zscore
from scipy.stats.mstats import winsorize

In [6]:
#Importing dataset
df = pd.read_csv("patient_health_records.csv")
df

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,10001,56.0,Male,West,34.96,113.91,472.44,100.03,0
1,10002,69.0,Female,NaN,26.96,128.06,189.30,83.43,0
2,10003,46.0,Female,West,32.95,134.16,NaN,96.50,1
3,10004,32.0,Female,NaN,22.15,122.93,226.38,101.68,0
4,10005,60.0,Female,East,21.01,144.98,174.47,108.81,1
...,...,...,...,...,...,...,...,...,...
4995,14996,42.0,NaN,North,22.06,120.62,NaN,66.28,0
4996,14997,39.0,Female,West,30.45,94.39,227.01,NaN,0
4997,14998,48.0,Female,East,26.91,136.98,155.77,97.86,0
4998,14999,34.0,Male,NaN,13.29,89.96,275.41,74.72,1
4999,15000,72.0,Female,South,26.50,113.75,235.73,124.45,0

In [7]:
print("\nMissing Values Count:")
print(df.isnull().sum())
print("\nPercentage of Missing Values:")
print((df.isnull().sum() / len(df) * 100).round(2))

Missing Values Count:
patient_id          0
age               500
gender            500
region            500
bmi               500
blood_pressure      0
cholesterol       500
glucose           500
disease_risk        0
dtype: int64

Percentage of Missing Values:
patient_id         0.0
age               10.0
gender            10.0
region            10.0
bmi               10.0
blood_pressure     0.0
cholesterol       10.0
glucose           10.0
disease_risk       0.0
dtype: float64

## Simple Imputer(Numerical)

In [5]:
# using simple imputer numrical for filling bmi missing valus using mean
num_imputer = SimpleImputer(strategy='mean')
df[['bmi']] = num_imputer.fit_transform(df[['bmi']])
print("After BMI Mean Imputation:")
df

After BMI Mean Imputation:

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,10001,56.0,Male,West,34.96,113.91,472.44,100.03,0
1,10002,69.0,Female,NaN,26.96,128.06,189.30,83.43,0
2,10003,46.0,Female,West,32.95,134.16,NaN,96.50,1
3,10004,32.0,Female,NaN,22.15,122.93,226.38,101.68,0
4,10005,60.0,Female,East,21.01,144.98,174.47,108.81,1
...,...,...,...,...,...,...,...,...,...
4995,14996,42.0,NaN,North,22.06,120.62,NaN,66.28,0
4996,14997,39.0,Female,West,30.45,94.39,227.01,NaN,0
4997,14998,48.0,Female,East,26.91,136.98,155.77,97.86,0
4998,14999,34.0,Male,NaN,13.29,89.96,275.41,74.72,1
4999,15000,72.0,Female,South,26.50,113.75,235.73,124.45,0

## Simple Imputer(Categorical)

In [6]:
# using simple imputer categorical for filling bmi missing valus using mean
cat_imputer = SimpleImputer(strategy='most_frequent')
df[['region']] = cat_imputer.fit_transform(df[['region']])
print("After Region Most Frequent Imputation:")
df

After Region Most Frequent Imputation:

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,10001,56.0,Male,West,34.96,113.91,472.44,100.03,0
1,10002,69.0,Female,South,26.96,128.06,189.30,83.43,0
2,10003,46.0,Female,West,32.95,134.16,NaN,96.50,1
3,10004,32.0,Female,South,22.15,122.93,226.38,101.68,0
4,10005,60.0,Female,East,21.01,144.98,174.47,108.81,1
...,...,...,...,...,...,...,...,...,...
4995,14996,42.0,NaN,North,22.06,120.62,NaN,66.28,0
4996,14997,39.0,Female,West,30.45,94.39,227.01,NaN,0
4997,14998,48.0,Female,East,26.91,136.98,155.77,97.86,0
4998,14999,34.0,Male,South,13.29,89.96,275.41,74.72,1
4999,15000,72.0,Female,South,26.50,113.75,235.73,124.45,0

## Most Frequent Imputation

In [16]:
df['gender'] = df['gender'].fillna(df['gender'].mode()[0])
df

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,10001,56.0,Male,West,34.96,113.91,472.44,100.03,0
1,10002,69.0,Female,South,26.96,128.06,189.30,83.43,0
2,10003,46.0,Female,West,32.95,134.16,NaN,96.50,1
3,10004,32.0,Female,South,22.15,122.93,226.38,101.68,0
4,10005,60.0,Female,East,21.01,144.98,174.47,108.81,1
...,...,...,...,...,...,...,...,...,...
4995,14996,42.0,Male,North,22.06,120.62,NaN,66.28,0
4996,14997,39.0,Female,West,30.45,94.39,227.01,NaN,0
4997,14998,48.0,Female,East,26.91,136.98,155.77,97.86,0
4998,14999,34.0,Male,South,13.29,89.96,275.41,74.72,1
4999,15000,72.0,Female,South,26.50,113.75,235.73,124.45,0

## Missing Indicator + Random Sampling

In [18]:
# Create indicator column
df['age_missing'] = df['age'].isnull().astype(int)

# Random sampling imputation
age_non_null = df['age'].dropna()

df.loc[df['age'].isnull(), 'age'] = np.random.choice(age_non_null, size=df['age'].isnull().sum())
df

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk,age_missing
0,10001,56.0,Male,West,34.96,113.91,472.44,100.03,0,0
1,10002,69.0,Female,South,26.96,128.06,189.30,83.43,0,0
2,10003,46.0,Female,West,32.95,134.16,NaN,96.50,1,0
3,10004,32.0,Female,South,22.15,122.93,226.38,101.68,0,0
4,10005,60.0,Female,East,21.01,144.98,174.47,108.81,1,0
...,...,...,...,...,...,...,...,...,...,...
4995,14996,42.0,Male,North,22.06,120.62,NaN,66.28,0,0
4996,14997,39.0,Female,West,30.45,94.39,227.01,NaN,0,0
4997,14998,48.0,Female,East,26.91,136.98,155.77,97.86,0,0
4998,14999,34.0,Male,South,13.29,89.96,275.41,74.72,1,0
4999,15000,72.0,Female,South,26.50,113.75,235.73,124.45,0,0

## KNN Imputer (Multivariate)

In [8]:
#Using knn to fill age, bmi, blood pressure, cholestrol, glucose columns
knn_imputer = KNNImputer(n_neighbors=5)
num_cols = ['age', 'bmi', 'blood_pressure', 'cholesterol', 'glucose']
df[num_cols] = knn_imputer.fit_transform(df[num_cols])
df

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,10001,56.0,Male,West,34.96,113.91,472.440,100.030,0
1,10002,69.0,Female,NaN,26.96,128.06,189.300,83.430,0
2,10003,46.0,Female,West,32.95,134.16,219.832,96.500,1
3,10004,32.0,Female,NaN,22.15,122.93,226.380,101.680,0
4,10005,60.0,Female,East,21.01,144.98,174.470,108.810,1
...,...,...,...,...,...,...,...,...,...
4995,14996,42.0,NaN,North,22.06,120.62,266.062,66.280,0
4996,14997,39.0,Female,West,30.45,94.39,227.010,101.688,0
4997,14998,48.0,Female,East,26.91,136.98,155.770,97.860,0
4998,14999,34.0,Male,NaN,13.29,89.96,275.410,74.720,1
4999,15000,72.0,Female,South,26.50,113.75,235.730,124.450,0

## MICE Algorithm

In [9]:

mice_imputer = IterativeImputer(random_state=42)
df[num_cols] = mice_imputer.fit_transform(df[num_cols])
df

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,10001,56.0,Male,West,34.96,113.91,472.440,100.030,0
1,10002,69.0,Female,NaN,26.96,128.06,189.300,83.430,0
2,10003,46.0,Female,West,32.95,134.16,219.832,96.500,1
3,10004,32.0,Female,NaN,22.15,122.93,226.380,101.680,0
4,10005,60.0,Female,East,21.01,144.98,174.470,108.810,1
...,...,...,...,...,...,...,...,...,...
4995,14996,42.0,NaN,North,22.06,120.62,266.062,66.280,0
4996,14997,39.0,Female,West,30.45,94.39,227.010,101.688,0
4997,14998,48.0,Female,East,26.91,136.98,155.770,97.860,0
4998,14999,34.0,Male,NaN,13.29,89.96,275.410,74.720,1
4999,15000,72.0,Female,South,26.50,113.75,235.730,124.450,0

# Handling Outliers

In [11]:
df_outliers = df.copy()

## Z-Score Method

In [15]:


# Numerical columns
num_cols = ['bmi', 'blood_pressure', 'cholesterol', 'glucose']

# Compute Z-scores
z_scores = np.abs(zscore(df_outliers[num_cols], nan_policy='omit'))

# Convert to DataFrame
z_df = pd.DataFrame(z_scores, columns=num_cols)

# Identify outliers (if any column > 3)
outlier_mask = (z_df > 3).any(axis=1)

# Add columns to original DataFrame
df_outliers['z_score_flag'] = outlier_mask

print("Using scipy zscore():")
print(f"  Outliers found : {outlier_mask.sum()}")
print(f"  Original rows  : {len(df_outliers)}")

# Show outliers
print("\nOutlier rows:")
print(df_outliers[df_outliers['z_score_flag']].head())

# Remove outliers
df_zscore = df_outliers[~df_outliers['z_score_flag']].copy()

print(f"\nDataFrame cleaned: {len(df_outliers)} → {len(df_zscore)} rows")

Using scipy zscore():
  Outliers found : 334
  Original rows  : 5000

Outlier rows:
    patient_id   age  gender region     bmi  blood_pressure  cholesterol  \
0        10001  56.0    Male   West  34.960          113.91       472.44
26       10027  55.0    Male   West  92.100          119.16       190.16
30       10031  50.0    Male    NaN  26.762          236.00       162.76
41       10042  45.0    Male  South  20.894          267.68       192.70
46       10047  79.0  Female  North  15.170          250.96       250.21

    glucose  disease_risk  z_score_flag
0    100.03             0          True
26    93.75             0          True
30    81.17             0          True
41   115.97             1          True
46    89.11             0          True

DataFrame cleaned: 5000 → 4666 rows

## IQR Method

In [16]:
df_iqr = df_outliers.copy()  # Create a copy so original data remains unchanged

# Loop through each numerical column to detect and remove outliers
for col in num_cols:
    
    # Calculate first quartile (25th percentile)
    Q1 = df_iqr[col].quantile(0.25)
    
    # Calculate third quartile (75th percentile)
    Q3 = df_iqr[col].quantile(0.75)
    
    # Compute Interquartile Range (spread of middle 50% data)
    IQR = Q3 - Q1
    
    # Define lower and upper bounds for acceptable values
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    # Keep only rows within the acceptable range (remove outliers)
    df_iqr = df_iqr[(df_iqr[col] >= lower) & (df_iqr[col] <= upper)]

# Print shape after removing outliers
print("After IQR:", df_iqr.shape)

After IQR: (4483, 10)

## Percentile Method

In [17]:
df_percentile = df_outliers.copy()  # Create a copy to preserve original dataset

# Loop through each numerical column to cap extreme values
for col in num_cols:
    
    # Calculate lower bound (1st percentile)
    lower = df_percentile[col].quantile(0.01)
    
    # Calculate upper bound (99th percentile)
    upper = df_percentile[col].quantile(0.99)
    
    # Replace values below lower and above upper with the boundary values
    # This caps outliers instead of removing rows
    df_percentile[col] = np.clip(df_percentile[col], lower, upper)

# Shape remains same because no rows are removed
print("After Percentile Capping:", df_percentile.shape)

After Percentile Capping: (5000, 10)

## Winsorization

In [18]:
df_winsor = df_outliers.copy()  # Create a copy to keep original data unchanged

# Loop through each numerical column
for col in num_cols:
    
    # Apply Winsorization:
    # limits=[0.01, 0.01] means:
    # - lowest 1% values → replaced with 1st percentile value
    # - highest 1% values → replaced with 99th percentile value
    df_winsor[col] = winsorize(df_winsor[col], limits=[0.01, 0.01])

# Shape remains unchanged because values are capped, not removed
print("After Winsorization:", df_winsor.shape)

After Winsorization: (5000, 10)

In [19]:
#Before vs After Outlier Treatment

print("Original Shape:", df_outliers.shape)
print("Z-score Shape:", df_zscore.shape)
print("IQR Shape:", df_iqr.shape)
print("Percentile Shape:", df_percentile.shape)
print("Winsor Shape:", df_winsor.shape)

Original Shape: (5000, 10)
Z-score Shape: (4666, 10)
IQR Shape: (4483, 10)
Percentile Shape: (5000, 10)
Winsor Shape: (5000, 10)

## Final Clean Dataset

In [20]:
# ─────────────────────────────────────────────
# Final Clean Dataset
# ─────────────────────────────────────────────

df_final = df.copy()  # Start with a fresh copy

# -------- Missing Value Handling --------

from sklearn.impute import SimpleImputer

# Numerical columns
num_cols = ['age', 'bmi', 'blood_pressure', 'cholesterol', 'glucose']

# Apply median imputation (robust to outliers)
num_imputer = SimpleImputer(strategy='median')
df_final[num_cols] = num_imputer.fit_transform(df_final[num_cols])

# Categorical columns
cat_imputer = SimpleImputer(strategy='most_frequent')
df_final[['region']] = cat_imputer.fit_transform(df_final[['region']])

# Fill gender using mode
df_final['gender'] = df_final['gender'].fillna(df_final['gender'].mode()[0])

# -------- Outlier Handling (IQR Method) --------

# Create a mask to filter all columns together
mask = pd.Series(True, index=df_final.index)

for col in num_cols:
    Q1 = df_final[col].quantile(0.25)
    Q3 = df_final[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    # Update mask instead of filtering repeatedly
    mask &= (df_final[col] >= lower) & (df_final[col] <= upper)

# Apply mask once
df_final = df_final[mask]

# -------- Final Check --------

print("Final Shape:", df_final.shape)
print("\nMissing Values:\n", df_final.isnull().sum())

Final Shape: (4483, 9)

Missing Values:
 patient_id        0
age               0
gender            0
region            0
bmi               0
blood_pressure    0
cholesterol       0
glucose           0
disease_risk      0
dtype: int64

# Brief Report

### 1. Most Effective Imputation Strategy

The most effective imputation strategy was **median imputation for numerical features** and **mode (most frequent) imputation for categorical features**. Median is robust to outliers and provides stable central values, making it suitable for features such as age, BMI, cholesterol, and glucose. Mode imputation ensures logical and consistent replacement for categorical variables like gender and region.

Although advanced techniques such as KNN and MICE imputation were applied, they are computationally more complex and were not necessary for this dataset. Simpler methods provided efficient and reliable results.

---

### 2. Best Outlier Handling Method

The **Interquartile Range (IQR) method** was the most effective for handling outliers. It identifies extreme values using the range between the first quartile (Q1) and third quartile (Q3), making it robust to skewed data distributions.

Compared to the Z-score method, IQR does not assume normal distribution and performs better on real-world data. Unlike percentile capping and Winsorization, which only limit extreme values, the IQR method removes unrealistic values entirely, improving data quality.

---

### 3. Improvement in Dataset Usability

Data cleaning significantly improved the usability of the dataset. Missing values were handled appropriately, ensuring completeness across all features. Outliers were treated, reducing noise and improving the reliability of the data.

As a result, the dataset became more consistent, accurate, and suitable for machine learning applications. The cleaned dataset is now well-prepared for tasks such as disease risk prediction.